# Generated by Django 2.2.5 on 2019-09-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0004_2_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Account'),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_webhooks',
            field=models.PositiveIntegerField(default=0, help_text='Number of webhooks that have yet to be successfully delivered (i.e., to return a 20x response) to the URLs you’ve specified.'),
            preserve_default=False,
        ),
    ]
