# Generated by Django 2.2.5 on 2019-09-26 23:06

from django.db import migrations, models
import django.db.models.deletion
import djstripe.models.webhooks


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0004_2_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Account'),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_webhooks',
            field=models.PositiveIntegerField(default=0, help_text='Number of webhooks that have yet to be successfully delivered (i.e., to return a 20x response) to the URLs you’ve specified.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookeventtrigger',
            name='endpoint_type',
            field=models.CharField(choices=[(djstripe.models.webhooks.EndpointType(1), 'ACCOUNT'), (djstripe.models.webhooks.EndpointType(2), 'CONNECT')], default=1, help_text='The endpoint type that this event was triggered from.', max_length=2),
            preserve_default=False,
        ),
    ]
